apiVersion: apps/v1
kind: Deployment
metadata:
  name: insightpdf
  labels:
    app: insightpdf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insightpdf
  template:
    metadata:
      labels:
        app: insightpdf
    spec:
      containers:
      - name: insightpdf
        image: <YOUR-IMAGE-URL>
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: insightpdf-service
spec:
  selector:
    app: insightpdf
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: insightpdf-route
spec:
  to:
    kind: Service
    name: insightpdf-service
  port:
    targetPort: 8501
  tls:
    termination: edge
